#pragma once
#include "Common.h"
#include "GraphicsSystem.h"
#include"Colors.h"
#include"Camera.h"
#include"VertexShader.h"
#include"PixeShader.h"
#include"VertexTypes.h"
#include"Mesh.h"
#include"ConstantBuffer.h"
#include"MeshBuffer.h"
#include"Texture.h"
#include"Sampler.h"
#include"MeshBuilder.h"
#include"DebugUI.h"
#include"SimpleDraw.h"
#include"LightTypes.h"
#include"Material.h"
#include"BlendState.h"
#include"RenderTarget.h"
#include"OBJLoader.h"

//Animation
#include"Keyframe.h"
#include"Animation.h"
#include"AnimationBuilder.h"
#include"Model.h"
#include"MeshIO.h"
#include"MaterialIO.h"

#include"Bone.h"
#include "Skeleton.h"
#include"SkeletonIO.h"
#include"AnimationClip.h"
#include"AnimationSet.h"
#include"AnimationIO.h"
#include"Animator.h"

